version: "3.9"
services:
  frontend-suite:
    container_name: frontend-suite
    build:
      context: ../contrib/docker
      dockerfile: react.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:delegated
    command: /bin/sh -c "while sleep 1000; do :; done"
